Add Mapperclass to project
janwendt/scrapy-toolbox pull request #1
Opened 2021-03-30 08:20 UTC by siper102

2021-03-30 08:28 UTC, janwendt requested changes
You have to change the readme accordingly

2021-03-30 13:26 UTC, janwendt requested changes

2021-03-30 13:26 UTC, janwendt commented on setup.py
> +        "console_scripts": ["toolbox=scrapy_toolbox.command_line:main"],
Rückgängig machen

2021-03-30 13:26 UTC, janwendt commented on scrapy_toolbox/mapper.py
> +        return contains
set(ids).issubset(set(item_fields))

2021-03-31 07:25 UTC, siper102 commented on setup.py
> +        "console_scripts": ["toolbox=scrapy_toolbox.command_line:main"],
gemacht

2021-03-31 07:25 UTC, siper102 commented on scrapy_toolbox/mapper.py
> +        return contains
Habe ich so in die Funktion eingefügt

2021-03-31 10:04 UTC, janwendt approved these changes

2021-03-31 10:04 UTC, merged